baseurl                 = "https://vilisimo.github.io/"
contentdir              = "content"
layoutdir               = "layouts"
publishdir              = "public"
theme                   = "emperor"
title                   = "Machine Code Never Lies"
builddrafts             = false
canonifyurls            = true
googleAnalytics         = "UA-113536003-1"
pluralizelisttitles     = false
languageCode            = "en-us"
enableGitInfo           = true
paginate                = 10
pygmentsUseClassic      = false
pygmentsStyle           = "friendly"

[Author]
name                    = "Simonas ViliÅ«nas"

[taxonomies]
category                = "categories"
tag                     = "tags"
language                = "languages"
tool                    = "tools"

[permalinks]
blog                    = "blog/:slug/"
projects                = "projects/:slug/"

[[menu.main]]
name                    = "Home"
weight                  = -130
identifier              = "home"
url                     = "/"

[[menu.main]]
name                    = "Blog"
weight                  = -120
identifier              = "blog"
url                     = "/blog/"

[[menu.main]]
name                    = "Projects"
weight                  = -110
identifier              = "projects"
url                     = "/projects/"

[[menu.main]]
name                    = "About"
weight                  = -100
identifier              = "about"
url                     = "/about/"

[params]
description             = "Blog about programming,"
latestpostcount         = 3
favicon                 = "img/lies.ico"

[params.assets]
normalizecss            = true

[params.social]
github                  = "vilisimo"
linkedin                = "simonasviliunas"
stackoverflow           = "4543382"