baseURL = "http://www.example.com"
publishDir = "public"
title = "Initial"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Temporary description"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Simonas Viliūnas"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
# codepen = "name"
# email = "contact@example.com"
# facebook = "name"
github = "vilisimo"
# instagram = "name"
linkedin = "simonasviliunas"
# twitter = "name"
telegram = "name"

[params.social.config]
# platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin","telegram"]
platforms = ["github","linkedin"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

# Configures how the URLs look for specific folders
[permalinks]
page = "/:slug/"
posts = "/posts/:title/"

[[menu.main]]
name = "home"
weight = 1 
identifier = "Home"
url = "/"

[[menu.main]]
name = "blog"
weight = 2 
identifier = "Blog"
url = "/posts/"

[[menu.main]]
name = "projects"
weight = 3
identifier = "Projects"
url = "/projects/"

[[menu.main]]
name = "about"
weight = 4  
identifier = "About"
url = "/about/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
