baseurl             = "https://vilisimo.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Simonas Viliunas"
title               = "Machine Code Never Lies"
disqusshortname     = "machinecodeneverlies" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-113536003-1"

[blackfriday]
hrefTargetBlank     = true

[permalinks]
blog  = "blog/:slug/"

[taxonomies]
tag                 = "tags"
category            = "categories"

[[menu.main]]
name                   = "Home"
weight                 = -130
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Projects"
weight                 = -110
identifier             = "projects"
url                    = "/projects/"

[[menu.main]]
name                   = "About"
weight                 = -100
identifier             = "about"
url                    = "/about/"

[params]
include_rss            = true                               # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                                  # how many posts to display on the home page
i18n_flags             = false                              # whether to display small country flags for available translations
title                  = "Machine Code Never Lies"          # Appears above menu items
description            = "Read the source code and weep"
intro                  = "Read the source code and weep"    # appears in the site header when set to a non-empty string
cachebuster            = true                               # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
faviconfile            = "img/lies.ico"
lang                   = "en"

# Additional JavaScript
customjs               = ["/js/custom.js"]
jquery                 = true

# Additional CSS
customcss              = ["/css/custom.css"]

# Social
github                 = "//github.com/vilisimo"
# email                  = "you@example.space"
# instagram              = "//instagram.com/you"
linkedin               = "//linkedin.com/in/simonasviliunas"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
# twitter                = "//twitter.com/you"

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik

# avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar               = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar
